In [1]:
import numpy as np
arr01 = np.array([11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
arr01

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [2]:
arr02 = np.arange(12,31,2)
arr02

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [3]:
arr03 = np.zeros((4,6))
arr03

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
arr04 = np.ones((4,6))
arr04

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [5]:
arr05 = np.linspace(6,8,11)
arr05

array([6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. ])

In [6]:
arr06 = np.linspace(0,20,41)
arr06

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [7]:
arr07 = np.identity(6)
arr07

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [8]:
arr08 = np.eye(4)
arr08

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
arr09 = np.random.rand(6,4)
arr09

array([[0.77375141, 0.59924579, 0.37017423, 0.29052281],
       [0.26644082, 0.29285127, 0.42664362, 0.96815071],
       [0.80282903, 0.92371831, 0.43186289, 0.47590984],
       [0.46754815, 0.80540718, 0.52196221, 0.84727776],
       [0.02649684, 0.22157935, 0.20402519, 0.4773761 ],
       [0.78865725, 0.7494257 , 0.36367001, 0.51317297]])

In [10]:
arr10 = np.random.randn(4,3)
arr10

array([[ 1.18923474,  1.50965852, -0.41925684],
       [-0.29097692,  1.13357141, -0.31139273],
       [-1.36752328, -0.02828115,  0.04419314],
       [ 0.12053419,  0.07607873,  1.40861856]])

In [11]:
arr11 = np.random.randint(1,101,200)
arr11

array([ 17,  84,  58,  22,  70,  78,  46,  76,  77,  14,  71,   7,  63,
        72,   5,  87,  41,  70,  93,  90,  29,  71,  78,  64,  19,  72,
        17,  33,  11,  89,   7,  69,  52,  84,  85,  27,  45,   4,  35,
        86,  11,   6,   1,  19,  54,  76,  72,  55,  85,  41,  71,  79,
        44,  41,  38,  12,  57,  60,  63,  42,  80,  83,   4,  35,  76,
        99,  75,  14,   6,  45,  41,  99,  60,  11,  61,  88,  35,  67,
        20,  45,  89,  95,  74,  70,  68,  48,  73,  98,  23,  47,  32,
        59,  26,  68,  66,  15,  83,  68,  95,  42,  61,  90,  26,  83,
        96,  23,  75,  46,  92,  63,  86,  16,  60,  81,  97,  48,  28,
        63,  29,  71,  97,  23,  23,  48,  27,  78,   4,  12,   5,   1,
        61,  68,  73,  28,  78,   9,  42,  49,  86,  83,  62,  98,  63,
        27,   8,  43,   6,  96,  63,  90,  98,  21,   7,  35,  50,  14,
        25,  85,  69,  92,  33,  11,  58,  79,   4,  91,  47,  35, 100,
        52,  48,  47,  48,  61,  20,  43,  72,  69,  77,  91,  4

In [12]:
arr12 = arr11.reshape(10,20)

In [13]:
arr12.max()

100

In [14]:
arr12.min()

1

In [15]:
arr12.mean()

53.505

In [16]:
arr12.argmax()

168

In [17]:
arr12.argmin()

42

In [18]:
arr12.shape

(10, 20)

In [19]:
arr12.dtype

dtype('int32')

In [20]:
arr11.shape

(200,)

In [21]:
arr13 = arr12.copy()
arr13

array([[ 17,  84,  58,  22,  70,  78,  46,  76,  77,  14,  71,   7,  63,
         72,   5,  87,  41,  70,  93,  90],
       [ 29,  71,  78,  64,  19,  72,  17,  33,  11,  89,   7,  69,  52,
         84,  85,  27,  45,   4,  35,  86],
       [ 11,   6,   1,  19,  54,  76,  72,  55,  85,  41,  71,  79,  44,
         41,  38,  12,  57,  60,  63,  42],
       [ 80,  83,   4,  35,  76,  99,  75,  14,   6,  45,  41,  99,  60,
         11,  61,  88,  35,  67,  20,  45],
       [ 89,  95,  74,  70,  68,  48,  73,  98,  23,  47,  32,  59,  26,
         68,  66,  15,  83,  68,  95,  42],
       [ 61,  90,  26,  83,  96,  23,  75,  46,  92,  63,  86,  16,  60,
         81,  97,  48,  28,  63,  29,  71],
       [ 97,  23,  23,  48,  27,  78,   4,  12,   5,   1,  61,  68,  73,
         28,  78,   9,  42,  49,  86,  83],
       [ 62,  98,  63,  27,   8,  43,   6,  96,  63,  90,  98,  21,   7,
         35,  50,  14,  25,  85,  69,  92],
       [ 33,  11,  58,  79,   4,  91,  47,  35, 100,  52,  48,  

In [22]:
arr14 = np.array ([ [12,14,16] , [18,20,22] , [24,26,28] , [30,32,34] ])
arr14

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [23]:
arr14[3][1]

32

In [24]:
arr14[3,1]

32

In [25]:
arr15 = arr14 > 23
arr15

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [26]:
arr14[arr15]

array([24, 26, 28, 30, 32, 34])

In [27]:
arr14 [ arr14 > 23 ]

array([24, 26, 28, 30, 32, 34])

In [28]:
arr16 = np.arange(1,49).reshape(8,6)
arr16

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48]])

In [29]:
arr17 = np.arange(11,41).reshape(5,6)
arr17

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40]])

In [30]:
arr18 = np.arange(202,262,2).reshape(5,6)
arr18

array([[202, 204, 206, 208, 210, 212],
       [214, 216, 218, 220, 222, 224],
       [226, 228, 230, 232, 234, 236],
       [238, 240, 242, 244, 246, 248],
       [250, 252, 254, 256, 258, 260]])

In [31]:
arr17 + arr18

array([[213, 216, 219, 222, 225, 228],
       [231, 234, 237, 240, 243, 246],
       [249, 252, 255, 258, 261, 264],
       [267, 270, 273, 276, 279, 282],
       [285, 288, 291, 294, 297, 300]])

In [32]:
arr18 - arr17

array([[191, 192, 193, 194, 195, 196],
       [197, 198, 199, 200, 201, 202],
       [203, 204, 205, 206, 207, 208],
       [209, 210, 211, 212, 213, 214],
       [215, 216, 217, 218, 219, 220]])

In [33]:
arr17 * arr18

array([[ 2222,  2448,  2678,  2912,  3150,  3392],
       [ 3638,  3888,  4142,  4400,  4662,  4928],
       [ 5198,  5472,  5750,  6032,  6318,  6608],
       [ 6902,  7200,  7502,  7808,  8118,  8432],
       [ 8750,  9072,  9398,  9728, 10062, 10400]])

In [34]:
arr17 * 4

array([[ 44,  48,  52,  56,  60,  64],
       [ 68,  72,  76,  80,  84,  88],
       [ 92,  96, 100, 104, 108, 112],
       [116, 120, 124, 128, 132, 136],
       [140, 144, 148, 152, 156, 160]])

In [35]:
arr17 + 100

array([[111, 112, 113, 114, 115, 116],
       [117, 118, 119, 120, 121, 122],
       [123, 124, 125, 126, 127, 128],
       [129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140]])

In [36]:
arr17 ** 2

array([[ 121,  144,  169,  196,  225,  256],
       [ 289,  324,  361,  400,  441,  484],
       [ 529,  576,  625,  676,  729,  784],
       [ 841,  900,  961, 1024, 1089, 1156],
       [1225, 1296, 1369, 1444, 1521, 1600]])

In [37]:
1 / arr17

array([[0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
        0.0625    ],
       [0.05882353, 0.05555556, 0.05263158, 0.05      , 0.04761905,
        0.04545455],
       [0.04347826, 0.04166667, 0.04      , 0.03846154, 0.03703704,
        0.03571429],
       [0.03448276, 0.03333333, 0.03225806, 0.03125   , 0.03030303,
        0.02941176],
       [0.02857143, 0.02777778, 0.02702703, 0.02631579, 0.02564103,
        0.025     ]])

In [38]:
arr18 / arr17

array([[18.36363636, 17.        , 15.84615385, 14.85714286, 14.        ,
        13.25      ],
       [12.58823529, 12.        , 11.47368421, 11.        , 10.57142857,
        10.18181818],
       [ 9.82608696,  9.5       ,  9.2       ,  8.92307692,  8.66666667,
         8.42857143],
       [ 8.20689655,  8.        ,  7.80645161,  7.625     ,  7.45454545,
         7.29411765],
       [ 7.14285714,  7.        ,  6.86486486,  6.73684211,  6.61538462,
         6.5       ]])

In [39]:
np.sqrt(arr18)

array([[14.2126704 , 14.28285686, 14.35270009, 14.4222051 , 14.49137675,
        14.56021978],
       [14.62873884, 14.69693846, 14.76482306, 14.83239697, 14.89966443,
        14.96662955],
       [15.03329638, 15.09966887, 15.16575089, 15.23154621, 15.29705854,
        15.3622915 ],
       [15.42724862, 15.49193338, 15.55634919, 15.62049935, 15.68438714,
        15.74801575],
       [15.8113883 , 15.87450787, 15.93737745, 16.        , 16.0623784 ,
        16.1245155 ]])

In [40]:
np.exp(arr17)

array([[5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06, 8.88611052e+06],
       [2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
        1.31881573e+09, 3.58491285e+09],
       [9.74480345e+09, 2.64891221e+10, 7.20048993e+10, 1.95729609e+11,
        5.32048241e+11, 1.44625706e+12],
       [3.93133430e+12, 1.06864746e+13, 2.90488497e+13, 7.89629602e+13,
        2.14643580e+14, 5.83461743e+14],
       [1.58601345e+15, 4.31123155e+15, 1.17191424e+16, 3.18559318e+16,
        8.65934004e+16, 2.35385267e+17]])

In [41]:
np.max(arr18)

260

In [42]:
np.min(arr18)

202

In [43]:
np.sin(arr18)

array([[ 0.80641841,  0.20212036, -0.9746419 ,  0.60906793,  0.46771852,
        -0.99834709],
       [ 0.36319945,  0.69605849, -0.94252453,  0.08839871,  0.86895084,
        -0.811621  ],
       [-0.19344382,  0.97262306, -0.6160642 , -0.45987672,  0.99881669,
        -0.37143209],
       [-0.68967611,  0.94544515, -0.09721191, -0.8645363 ,  0.81676   ,
         0.18475212],
       [-0.97052802,  0.62301221,  0.4519989 , -0.99920803,  0.37963563,
         0.6832397 ]])

In [44]:
np.cos(arr18)

array([[ 0.59134538, -0.97936069,  0.22377033,  0.79311806, -0.88387747,
        -0.05747243],
       [ 0.93171141, -0.71798508, -0.33413697,  0.99608517, -0.49489841,
        -0.58418435],
       [ 0.98111135, -0.23238842, -0.78769594,  0.88798277,  0.0486335 ,
        -0.92846012],
       [ 0.72411799,  0.32578131, -0.99526371,  0.50257038,  0.57697756,
        -0.98278515],
       [ 0.24098831,  0.78221211, -0.8920185 , -0.03979076,  0.92513609,
        -0.73019416]])

In [45]:
np.tan(arr18)

array([[ 1.36370121, -0.2063799 , -4.35554572,  0.76794107, -0.52916669,
        17.37088686],
       [ 0.38981969, -0.96946093,  2.82077294,  0.08874614, -1.75581657,
         1.38932341],
       [-0.19716805, -4.18533358,  0.78210915, -0.51788924, 20.53762695,
         0.40005174],
       [-0.9524361 ,  2.90208535,  0.09767452, -1.72022931,  1.41558365,
        -0.18798831],
       [-4.02728265,  0.79647477, -0.50671472, 25.11155946,  0.41035652,
        -0.93569593]])

In [46]:
np.log(arr18)

array([[5.3082677 , 5.31811999, 5.32787617, 5.33753808, 5.34710753,
        5.35658627],
       [5.36597602, 5.37527841, 5.38449506, 5.39362755, 5.40267738,
        5.41164605],
       [5.420535  , 5.42934563, 5.43807931, 5.44673737, 5.45532112,
        5.46383181],
       [5.47227067, 5.48063892, 5.48893773, 5.49716823, 5.50533154,
        5.51342875],
       [5.52146092, 5.52942909, 5.53733427, 5.54517744, 5.55295958,
        5.56068163]])

In [47]:
np.log10(arr18)

array([[2.30535137, 2.30963017, 2.31386722, 2.31806333, 2.32221929,
        2.32633586],
       [2.33041377, 2.33445375, 2.33845649, 2.34242268, 2.34635297,
        2.35024802],
       [2.35410844, 2.35793485, 2.36172784, 2.36548798, 2.36921586,
        2.372912  ],
       [2.37657696, 2.38021124, 2.38381537, 2.38738983, 2.39093511,
        2.39445168],
       [2.39794001, 2.40140054, 2.40483372, 2.40823997, 2.41161971,
        2.41497335]])

In [48]:
np.log2(arr18)

array([[7.65821148, 7.67242534, 7.68650053, 7.70043972, 7.71424552,
        7.72792045],
       [7.74146699, 7.7548875 , 7.76818432, 7.78135971, 7.79441587,
        7.80735492],
       [7.82017896, 7.83289001, 7.84549005, 7.857981  , 7.87036472,
        7.88264305],
       [7.89481776, 7.9068906 , 7.91886324, 7.93073734, 7.94251451,
        7.95419631],
       [7.96578428, 7.97727992, 7.98868469, 8.        , 8.01122726,
        8.02236781]])

In [49]:
arr19 = np.ones(10) * 6
arr19

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [50]:
arr20 = np.zeros(10) + 8
arr20

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [51]:
arr21 = np.arange(1,26).reshape(5,5)
arr21

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
arr21[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [53]:
arr21 [ 0:3 , 1 ]

array([ 2,  7, 12])

In [54]:
arr21 [ 0:3 , 1:2 ]

array([[ 2],
       [ 7],
       [12]])

In [55]:
np.sum(arr21)

325

In [56]:
np.std(arr21)

7.211102550927978

In [57]:
np.sum ( arr21 , axis=0 )

array([55, 60, 65, 70, 75])

In [58]:
arr22 = np.zeros(4) + np.ones(4) + np.eye(4) + np.identity(4)
arr22

array([[3., 1., 1., 1.],
       [1., 3., 1., 1.],
       [1., 1., 3., 1.],
       [1., 1., 1., 3.]])